version: "3"
services:
  srv:
    build:
      context: ./
    ports:
      - 8888:8888
    volumes:
      - ./work:/home/jovyan/work
      - ./config:/home/jovyan/.jupyter
    working_dir: /home/jovyan/work
    tty: true
